services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - api
    networks:
      - ausemart-network

  api:
    build:
      context: ./AusemartApi
      dockerfile: Dockerfile
    ports:
      - "8050:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - ausemart-network

networks:
  ausemart-network:
    driver: bridge